/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as MinasRouteImport } from './routes/minas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinasRoute = MinasRouteImport.update({
  id: '/minas',
  path: '/minas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estatisticas': typeof EstatisticasRoute
  '/minas': typeof MinasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estatisticas': typeof EstatisticasRoute
  '/minas': typeof MinasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estatisticas': typeof EstatisticasRoute
  '/minas': typeof MinasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/calculadora' | '/configuracoes' | '/estatisticas' | '/minas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calculadora' | '/configuracoes' | '/estatisticas' | '/minas'
  id:
    | '__root__'
    | '/'
    | '/calculadora'
    | '/configuracoes'
    | '/estatisticas'
    | '/minas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculadoraRoute: typeof CalculadoraRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EstatisticasRoute: typeof EstatisticasRoute
  MinasRoute: typeof MinasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minas': {
      id: '/minas'
      path: '/minas'
      fullPath: '/minas'
      preLoaderRoute: typeof MinasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculadoraRoute: CalculadoraRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EstatisticasRoute: EstatisticasRoute,
  MinasRoute: MinasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
